gemfile: Gemfile

concurrency: '1'

PrePush:
  CustomScript:
    enabled: true
    command: ["ruby", "bin/pre-push.rb"]

PreCommit:
  BundleCheck:
    enabled: true

  CustomScript:
    enabled: true
    command: ["ruby" ,"bin/pre-commit.rb"]